### PR TITLE
Readme to inform compatibility with Gnome 41

### PR DESCRIPTION
**Pull request by mmalafaia**
Updated Readme to inform compatibility with Gnome 41

### CODE REVIEW

**Comment by thaitzer** [comment]
Since Fedora 35 is already released and it is running Gnome 41, I would love to get one of my favorite extensions back. So please merge this, if that is all that is necessary to make it work on 41.

**Comment by larouxn** [comment]
Functional compatability with GNOME 41 was added via https://github.com/kgshank/gse-sound-output-device-chooser/pull/181. Thus, we _can_ install this extension manually following [these steps](https://github.com/kgshank/gse-sound-output-device-chooser/tree/2fc2cbc8a01f3574ccdccf6ece2cf57eba6373e0#installation-instructions). That said, I agree that ideally we update the README via this PR and publish a release to [extensions.gnome.org](https://extensions.gnome.org/extension/906/sound-output-device-chooser/).

:tophat: :tophat: :tophat: :tophat: :tophat: (tested with GNOME 41 on Fedora 35)
Screenshot from 2021-11-06 09-43-14
Screenshot from 2021-11-06 09-49-23

**Comment by ShrirajHegde** [comment]
> Since Fedora 35 is already released and it is running Gnome 41, I would love to get one of my favorite extensions back. So please merge this, if that is all that is necessary to make it work on 41.

`gsettings set org.gnome.shell "disable-extension-version-validation" true ` use this until release

**Comment by ShrirajHegde** [comment]
> Functional compatability with GNOME 41 was added via #181. Thus, we _can_ install this extension manually following [these steps](https://github.com/kgshank/gse-sound-output-device-chooser/tree/2fc2cbc8a01f3574ccdccf6ece2cf57eba6373e0#installation-instructions). 

@larouxn,
Is the screenshot from Fedora 35? Extension settings and extension app doesn't seem to follow dark theme for me on Fedora 35 for some unknown reason.

**Comment by kgshank** [comment]
Thanks for the support, will push an update in this week

**Comment by larouxn** [comment]
> > Functional compatability with GNOME 41 was added via #181. Thus, we _can_ install this extension manually following [these steps](https://github.com/kgshank/gse-sound-output-device-chooser/tree/2fc2cbc8a01f3574ccdccf6ece2cf57eba6373e0#installation-instructions).
> 
> @larouxn, Is the screenshot from Fedora 35? Extension settings and extension app doesn't seem to follow dark theme for me on Fedora 35 for some unknown reason.

Yes, the screenshots are from Fedora 35 in "dark mode" via GNOME Tweaks → theme → "Adawaita-dark". Also installed [user-themes](https://extensions.gnome.org/extension/19/user-themes/) extension + [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icons, for what it's worth.


> Thanks for the support, will push an update in this week

Glad to help in any way. Thank you! 🙇‍♂️

**Comment by ShrirajHegde** [comment]
> Yes, the screenshots are from Fedora 35 in "dark mode" via GNOME Tweaks → theme → "Adawaita-dark". Also installed [user-themes](https://extensions.gnome.org/extension/19/user-themes/) extension + [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icons, for what it's worth.

Oh yeah, Extensions aren't being themed only for HighContrastInverse. Advaita Dark works fine.

**Pull request merged**
