### PR TITLE
Combine Widget Dropdown With Audio Level Control Slider (feature #167)

### PR DESCRIPTION
**Pull request by thesmallcreeper**
So... I combined widget dropdown with audio level control slider as requested at #167 from @PerryHugh . (tbh that was a cool idea)
The feature can be enabled from Prefs->"Integrate selector with slider" (default is false)

I should note some things:

- Most preferences work as expected when integration of selector with slider is enabled. However "Display icons only in selection list" has no effect.
- Enabling/Disabling on the fly implementation is kinda scuffed. All it does is disabling and then enabling the extension. We might want a better way.
- The volume_patch.js is a modified version of [volume.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/status/volume.js). (We might need to see what is going on with licensing)
- I am not experienced with JS or Gnome that much so a good code review might be needed. I guess some things can improve.

As always feel free to make edits and ask for changes. 
Every opinion welcomed!
I will sign off with some screenshots!
Thank you :)

Enabled with "Show volume control for default device" also enabled
Screenshot from 2021-08-13 18-58-06

Enabled with "Show volume control for default device" also enabled but "Show input devices" disabled
Screenshot from 2021-08-13 18-58-26

Enabled with "Show volume control for default device" disabled
Screenshot from 2021-08-13 18-57-40

### CODE REVIEW

**Comment by PerryHugh** [comment]
Oh hell yeah, this is perfect! I hope it gets merged soon!

**Comment by kgshank** [comment]
@thesmallcreeper Thanks a lot for active participation. One request from myside, I dont have much time to check feasibility, so if possible, see whether the upstream volume.js can be avoided, like using subclass etc. It will be nightmare every time , when there is a new gnome release, just to bring the upstream changes and checking the compatibility with older shell versions alone. If there is no other feasibility, then the supported shell version should be updated and older shell version shell versions should be dropped except whatever you tested the extension, possible v40+. Please let me know your findings.

I am really sorry, I am not merging the request now.

**Comment by thesmallcreeper** [comment]
@kgshank My edits on volume.js are also on constructors, from my googleing making subclasses and then overriding constructors might not possible, note that super constructor must be called on subclasses. As I mentioned I am not experienced on JS so please if you have any idea let me know. :)

It works just fine on Gnome 40. Haven't tested on something else. However on [history of volume.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/commits/main/js/ui/status/volume.js) this looks like [the latest commit that change the interaction with the rest of Gnome](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/104071acbdf16ac0a667c588eb60b418df8b1955) (actually [this](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/5af8bf27885d35d9027e961ea516a5dd4cfe9d53) is the latest but added back a removed by accident feature). This (and the other add back commit) put us at [3.35.2 tag](https://gitlab.gnome.org/GNOME/gnome-shell/-/commits/3.35.2). Of course I might have missed something but I have some confidence on it.

Now that I am writing all these I am thinking of this, gonna burn some USBs with old Ubuntu and get into "Live CD" and try out. So will report back my findings.

One last thing, if you check `extension.js` I don't initialize something from `volume_patch.js` except if the user would like to have this feature. I mean if it ain't work we ain't break the features of the extension already there.

**Comment by thesmallcreeper** [comment]
Did some testing with Live USDs,

Gnome-shell 3.34.1 fails :disappointed:.
Gnome-shell 3.36.9 works :smile: . (had to upgrade to .9 because there was a bug on gnome side of things opening prefs)

For the record 3.34.1 hits on `volume.js->StreamSlider->_changeSlider()->this._slider.(un)block_signal_handler(...)` which blames [this commit](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/284ace5b5f86990325970a94e68ef687f52f4bdf).

**Comment by jacksongoode** [comment]
What would be keeping this PR from merging at this point @kgshank ?

**Comment by thesmallcreeper** [comment]
@jacksongoode The fear that maintaining the feature across future Gnome release will be difficult. I had a look how I could refactor the changes to make them more futureproof but due to some limitation of JS I couldn't.

Imo this is a step forward for the extension so it worth the "pain" like once a year.

Btw right now there are some stupid merge conflicts. @kgshank hit me up to fix them if you want to merge this PR. :)

**Comment by kgshank** [comment]
@thesmallcreeper  I have implemented your idea with no patches to the volume.js. I have partially merged your changes, so closing this Pull Request. Please test and update your issues in the tracking ticket. As always, thanks a lot for your continuous support and contributions.

**Pull request closed without merging**
