### PR TITLE
Add default icon of 'audio-card' for sinks whose icon is null (happen…

### PR DESCRIPTION
**Pull request by acabal**
…s often with network sinks)

### CODE REVIEW

**Comment by acabal** [comment]
I included another tweak which doesn't add an empty \n() to the sink menuitem if the card origin is blank.  This usually happens with network sinks.

**Comment by acabal** [comment]
I have an additional commit for network sinks, if you're interested.

If a network sink is available on both ipv4 and ipv6, two entries for the same sink will appear in Gnome's sound settings, and thus in this extension's menu.  The names reported by the sinks are exactly the same, and they both connect to the same sink, so it's a useless duplicate.  A quick check will prevent this extra entry from being added to the extension's menu.

The duplicate sink issue is probably something that can be fixed with an arcane pulseaudio configuration, but as far as I can tell it's the default.  So not sure if you want to include that kind of check in the extension.  But, I'm personally using the code to remove duplicates :)

**Comment by kgshank** [comment]
Please commit the changes for duplicate removal. I will merge them, I have some other changes pending to be committed. I can include your changes as well for the next update.

**Comment by acabal** [comment]
I discovered a workaround for the duplicate sinks issue, for anyone who's interested.  Since PA uses Avahi to discover remote sinks, disabling ipv6 in Avahi will prevent PA from picking up both the ipv4 and the duplicate ipv6 sink.  This works great for me because I only use Avahi for PA remote sinks and nothing else.  You can disable ipv6 in Avahi with:

    sudo sed -i "s/use\-ipv6\=yes/use-ipv6=no/g" /etc/avahi/avahi-daemon.conf

Then reboot your computer.

This makes a patch for duplicate sinks unnecessary.  Sorry for the late reply!

**Pull request merged**
